optimo_arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.0050000000000000001
  kinematics_solver_timeout: 0.0050000000000000001
  # taken from https://github.com/orgs/moveit/discussions/1950
  # kinematics_solver: pick_ik/PickIkPlugin
  # kinematics_solver_timeout: 0.1
  # mode: local
  # rotation_scale: 1.0
  # # position_threshold: 0.01
  # # orientation_threshold: 0.01 #since we are servoing, we do not want to allow any flexibility in the command
  # cost_threshold: 0.1
  # minimal_displacement_weight: 0.001
  # gd_step_size: 0.0001
