#Used for ros2 control, not simulation
/**/controller_manager:
  ros__parameters:
    update_rate: 1000 # Hz
    use_realtime_priority: true
    thread_priority: 90

    optimo_effort_controller:
      type: optimo_controllers/OptimoEffortController

    gripper_position_controller:
      type: position_controllers/JointGroupPositionController

    gripper_effort_controller:
      type: effort_controllers/JointGroupEffortController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

/**/optimo_effort_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
    robot_index: 0
    robot_prefix: ""

/**/gripper_position_controller:
  ros__parameters:
    joints:
      - left_finger_joint
    robot_index: 0

/**/gripper_effort_controller:
  ros__parameters:
    joints:
      - left_finger_joint
    robot_index: 0

/**/joint_state_broadcaster:
  ros__parameters:
    update_rate: 100 # Hz, but if main loop slows this also slows
